- hosts: load-balancer
  become: yes  
  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar HAProxy
      apt:
        name: haproxy
        state: present

